### ISSUE TITLE
Fix NullPointerException bug

### ISSUE THREAD

**Issue by talhakum** [talhakum/CrewFinder#10]
Image below shows the exception:

<img width="1342" alt="screen shot 2018-03-24 at 13 05 12" src="https://user-images.githubusercontent.com/12021578/37863311-007b441c-2f65-11e8-979c-5252c755a3d2.png">

An example case that exception comes: Attend a group via one device. Create a group with the same name of the attended before on another device.

**Comment by fatihdurukan** [comment]
Solved.

**Comment by fatihdurukan** [comment]
Solved.
